"use client";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import WorldScene3D from "./WorldScene3D";
import { createWorld } from "@/lib/seed";
import { applyAiActions, tickWorld, triggerEconomy, triggerWeather } from "@/lib/engine";
import type { Agent, AiAction, CountryId, WeatherKind, WorldState } from "@/lib/types";

type Tab="fuqaro"|"yozishma"|"aiogram"|"insta"|"yangilik"|"boshqaruv";
const STORAGE="ai-earth-real3d-v3";
const weatherLabel:Record<WeatherKind,string>={ochiq:"Ochiq",yomgir:"Yomg‘ir",issiq:"Jazirama",boron:"Bo‘ron",toshqin:"Toshqin",yongin:"Yong‘in",qor:"Qor"};
const activityLabel:Record<string,string>={uxlash:"Uxlayapti",uyda:"Uyda",ish:"Ishlayapti",ovqat:"Ovqatlanyapti",xarid:"Xarid qilyapti",suhbat:"Suhbatlashyapti",sayr:"Sayr qilyapti",yolda:"Yo‘lda",panoh:"Panoh izlayapti",shifoxona:"Shifoxonada"};
function fmtTime(w:WorldState){const h=Math.floor(w.minute/60)%24,m=Math.floor(w.minute%60);return `${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}`;}
function fmtAt(at:number){const d=Math.max(1,Math.floor(at/1440));const mm=((at%1440)+1440)%1440,h=Math.floor(mm/60),m=Math.floor(mm%60);return `${d}-kun ${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}`;}
function clone<T>(x:T):T{return typeof structuredClone==="function"?structuredClone(x):JSON.parse(JSON.stringify(x)) as T;}
function meter(v:number){return <div className="meter"><span style={{width:`${Math.max(0,Math.min(100,v))}%`}}/></div>}
function AgentCard({a,onClick,selected}:{a:Agent;onClick:()=>void;selected:boolean}){return <button className={`agentRow ${selected?"selected":""}`} onClick={onClick}><span className="agentDot"/><span><b>{a.name}</b><small>{a.job} · {activityLabel[a.activity]||a.activity}</small></span><em>{Math.round(a.money)}$</em></button>}
export default function WorldApp(){
  const [world,setWorld]=useState<WorldState>(()=>createWorld());
  const [ready,setReady]=useState(false);const [tab,setTab]=useState<Tab>("fuqaro");const [selectedAgentId,setSelectedAgentId]=useState<string|null>(null);const [selectedCountryId,setSelectedCountryId]=useState<CountryId>("zarrin");const [follow,setFollow]=useState(false);const [panelOpen,setPanelOpen]=useState(true);const [aiStatus,setAiStatus]=useState("Mahalliy miya");const lastReal=useRef(performance.now());const aiBusy=useRef(false);const worldRef=useRef(world);
  useEffect(()=>{worldRef.current=world;},[world]);
  useEffect(()=>{try{const raw=localStorage.getItem(STORAGE);if(raw){const parsed=JSON.parse(raw) as WorldState;if(parsed.version===3)setWorld(parsed);}}catch{}setReady(true);},[]);
  useEffect(()=>{if(!ready)return;const id=setInterval(()=>{setWorld(prev=>{const next=clone(prev);const now=performance.now(),dt=Math.min(1,(now-lastReal.current)/1000);lastReal.current=now;return tickWorld(next,dt);});},180);return()=>clearInterval(id);},[ready]);
  useEffect(()=>{if(!ready)return;const id=setInterval(()=>{try{localStorage.setItem(STORAGE,JSON.stringify(worldRef.current));}catch{}},3000);return()=>clearInterval(id);},[ready]);
  const selectedAgent=selectedAgentId?world.agents.find(a=>a.id===selectedAgentId)??null:null;
  const selectedCountry=world.countries.find(c=>c.id===selectedCountryId)??world.countries[0]!;
  const selectedMessages=useMemo(()=>selectedAgent?world.messages.filter(m=>m.fromId===selectedAgent.id||m.toId===selectedAgent.id).slice(0,70):world.messages.slice(0,70),[world.messages,selectedAgent]);
  const selectedPosts=useMemo(()=>selectedAgent?world.posts.filter(p=>p.authorId===selectedAgent.id||p.comments.some(c=>c.authorId===selectedAgent.id)):world.posts,[world.posts,selectedAgent]);
  const aiPulse=useCallback(async()=>{const current=worldRef.current;if(aiBusy.current||!current.aiBrain)return;const now=current.day*1440+current.minute;const candidates=current.agents.filter(a=>a.aiCooldownUntil<=now).sort((a,b)=>b.social-a.social).slice(0,5);if(!candidates.length)return;aiBusy.current=true;setAiStatus("Gemini o‘ylayapti…");try{const agents=candidates.map(a=>{const c=current.countries.find(x=>x.id===a.countryId)!;return{id:a.id,name:a.name,job:a.job,personality:a.personality,goal:a.goal,mood:a.mood,activity:a.activity,money:Math.round(a.money),hunger:Math.round(a.hunger),energy:Math.round(a.energy),friends:a.friends.map(id=>current.agents.find(x=>x.id===id)).filter(Boolean).map(x=>({id:x!.id,name:x!.name})),memories:a.memories.slice(0,5).map(m=>m.text),country:c.name,weather:weatherLabel[c.weather],recentPosts:current.posts.slice(0,8).map(p=>`${p.authorName}: ${p.text}`)}});const r=await fetch("/api/think",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({agents})});const data=await r.json() as {actions?:AiAction[];source?:string;warning?:string};if(data.actions?.length)setWorld(prev=>{const next=clone(prev);applyAiActions(next,data.actions!);next.aiLastPulse=next.day*1440+next.minute;return next;});setAiStatus(data.source==="gemini"?"Gemini faol":"Mahalliy miya");}catch{setAiStatus("Mahalliy miya");}finally{aiBusy.current=false;}},[]);
  useEffect(()=>{if(!ready||!world.aiBrain)return;const id=setInterval(()=>{void aiPulse();},16000);return()=>clearInterval(id);},[ready,world.aiBrain,aiPulse]);
  function mutate(fn:(w:WorldState)=>void){setWorld(prev=>{const next=clone(prev);fn(next);return next;});}
  function selectAgent(id:string){const a=world.agents.find(x=>x.id===id);setSelectedAgentId(id);if(a)setSelectedCountryId(a.countryId);setPanelOpen(true);setTab("fuqaro");}
  function reset(){if(!confirm("Dunyoni boshidan yaratamizmi? Hozirgi tarix o‘chadi."))return;localStorage.removeItem(STORAGE);setSelectedAgentId(null);setWorld(createWorld(Date.now()%999999));}
  function exportWorld(){const blob=new Blob([JSON.stringify(world,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`ai-yer-${world.day}-kun.json`;a.click();URL.revokeObjectURL(url);}
  if(!ready)return <main className="loading"><div className="spinner"/><b>3D dunyo uyg‘onyapti…</b></main>;
  return <main className="appShell">
    <section className="worldStage"><WorldScene3D world={world} selectedAgentId={selectedAgentId} follow={follow} onSelectAgent={selectAgent} selectedCountryId={selectedCountryId}/>
      <header className="topHud"><div className="brand"><span className="liveDot"/><div><b>AI YER — HAQIQIY 3D</b><small>100 mustaqil fuqaro · {aiStatus}</small></div></div><div className="clock"><b>{world.day}-KUN</b><strong>{fmtTime(world)}</strong></div><div className="speedGroup">{([0,1,5,20] as const).map(s=><button key={s} className={world.speed===s?"on":""} onClick={()=>mutate(w=>{w.speed=s})}>{s===0?"II":`${s}×`}</button>)}</div><button className="glassBtn" onClick={()=>setPanelOpen(v=>!v)}>{panelOpen?"Panelni yopish":"Panelni ochish"}</button></header>
      <div className="mapHint">Sichqoncha: aylantirish/yaqinlashtirish · Fuqaroni bosing: kuzatish</div>
      <div className="countryStrip">{world.countries.map(c=><button key={c.id} className={selectedCountryId===c.id?"on":""} onClick={()=>{setSelectedCountryId(c.id);setSelectedAgentId(null)}}><i style={{background:c.color}}/><span>{c.name}</span><small>{weatherLabel[c.weather]} · {Math.round(c.happiness)}%</small></button>)}</div>
      <div className="eventTicker">{world.events.slice(0,3).map(e=><span key={e.id}>◉ {e.text}</span>)}</div>
    </section>
    {panelOpen&&<aside className="sidePanel">
      <nav className="tabs">{([['fuqaro','Fuqaro'],['yozishma','Yozishmalar'],['aiogram','AIogram'],['insta','InstaAIgram'],['yangilik','Yangilik'],['boshqaruv','Xudo rejimi']] as [Tab,string][]).map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}</nav>
      <div className="panelBody">
        {tab==="fuqaro"&&<>{selectedAgent?<div className="profile"><div className="profileHead"><div className="avatar3d">◉</div><div><h2>{selectedAgent.name}</h2><p>{selectedAgent.age} yosh · {selectedAgent.job}</p><span>{world.countries.find(c=>c.id===selectedAgent.countryId)?.name}</span></div></div><div className="thought"><small>HOZIR NIMA O‘YLAYAPTI</small><b>{selectedAgent.thought}</b></div><div className="stat"><span>Energiya <b>{Math.round(selectedAgent.energy)}%</b></span>{meter(selectedAgent.energy)}</div><div className="stat"><span>Ochlik <b>{Math.round(selectedAgent.hunger)}%</b></span>{meter(selectedAgent.hunger)}</div><div className="stat"><span>Ijtimoiy ehtiyoj <b>{Math.round(selectedAgent.social)}%</b></span>{meter(selectedAgent.social)}</div><div className="detailGrid"><div><small>Kayfiyat</small><b>{selectedAgent.mood}</b></div><div><small>Hozir</small><b>{activityLabel[selectedAgent.activity]}</b></div><div><small>Pul</small><b>{Math.round(selectedAgent.money)}$</b></div><div><small>Do‘stlari</small><b>{selectedAgent.friends.length}</b></div></div><div className="bioBox"><small>XARAKTER</small><p>{selectedAgent.personality}</p><small>MAQSAD</small><p>{selectedAgent.goal}</p></div><button className={`followBtn ${follow?"on":""}`} onClick={()=>setFollow(v=>!v)}>{follow?"✓ Kamera kuzatyapti":"▶ Fuqaroni kamera bilan kuzatish"}</button><h3>So‘nggi xotiralari</h3>{selectedAgent.memories.length?selectedAgent.memories.slice(0,8).map(m=><div className="memory" key={m.id}><small>{fmtAt(m.at)}</small>{m.text}</div>):<p className="empty">Hali muhim xotira yo‘q.</p>}</div>:<><div className="sectionTitle"><div><h2>{selectedCountry.name}</h2><p>{selectedCountry.capital} · 20 fuqaro</p></div></div><div className="countryStats"><div><b>{Math.round(selectedCountry.happiness)}%</b><small>Baxt</small></div><div><b>{Math.round(selectedCountry.food)}%</b><small>Oziq-ovqat</small></div><div><b>{Math.round(selectedCountry.energy)}%</b><small>Energiya</small></div></div><h3>Fuqarolar</h3><div className="agentList">{world.agents.filter(a=>a.countryId===selectedCountryId).map(a=><AgentCard key={a.id} a={a} selected={false} onClick={()=>selectAgent(a.id)}/>)}</div></>}</>}
        {tab==="yozishma"&&<><div className="sectionTitle"><div><h2>{selectedAgent?`${selectedAgent.name} yozishmalari`:"Jonli yozishmalar"}</h2><p>Agentlar bir-biriga nima yozayotganini shu yerda ko‘rasiz.</p></div></div><div className="chatFeed">{selectedMessages.length?selectedMessages.map(m=>{const mine=selectedAgent&&m.fromId===selectedAgent.id;return <div key={m.id} className={`chatLine ${mine?"mine":""}`}><div className="chatMeta"><b>{m.fromName}</b><span>→ {m.toName}</span><small>{fmtAt(m.at)}</small></div><p>{m.text}</p></div>}):<p className="empty">Hozircha yozishma yo‘q. Vaqtni 5× yoki 20× qiling.</p>}</div></>}
        {tab==="aiogram"&&<><div className="sectionTitle"><div><h2>AIogram</h2><p>Shaxsiy xabarlar va jamiyatdagi suhbatlar.</p></div></div><div className="chatFeed">{world.messages.slice(0,100).map(m=><div key={m.id} className="chatLine"><div className="chatMeta"><b>{m.fromName}</b><span>→ {m.toName}</span><small>{fmtAt(m.at)}</small></div><p>{m.text}</p></div>)}</div></>}
        {tab==="insta"&&<><div className="sectionTitle"><div><h2>InstaAIgram</h2><p>Fuqarolarning o‘zlari yaratadigan ijtimoiy tarmoq.</p></div></div><div className="postFeed">{(selectedAgent?selectedPosts:world.posts).filter(p=>p.network==="insta").slice(0,80).map(p=><article className="post" key={p.id}><header><b>{p.authorName}</b><small>{fmtAt(p.at)}</small></header><p>{p.text}</p><footer>♥ {p.likes} · 💬 {p.comments.length}</footer>{p.comments.slice(0,4).map(c=><div className="comment" key={c.id}><b>{c.authorName}</b> {c.text}</div>)}</article>)}</div></>}
        {tab==="yangilik"&&<><div className="sectionTitle"><div><h2>AI Yangiliklar</h2><p>Dunyoda ro‘y berayotgan hodisalar arxivi.</p></div></div><div className="newsFeed">{world.events.slice(0,100).map(e=><article key={e.id}><small>{fmtAt(e.at)}</small><b>{e.text}</b></article>)}</div></>}
        {tab==="boshqaruv"&&<><div className="sectionTitle"><div><h2>Xudo rejimi</h2><p>{selectedCountry.name} uchun hodisa yuboring. Agentlar oqibatiga o‘zlari reaksiya qiladi.</p></div></div><div className="countrySelect">{world.countries.map(c=><button key={c.id} onClick={()=>setSelectedCountryId(c.id)} className={c.id===selectedCountryId?"on":""}><i style={{background:c.color}}/>{c.name}</button>)}</div><h3>Ob-havo va ofatlar</h3><div className="godGrid"><button onClick={()=>mutate(w=>triggerWeather(w,selectedCountryId,"ochiq",2))}>☀️<b>Ochiq havo</b></button><button onClick={()=>mutate(w=>triggerWeather(w,selectedCountryId,"yomgir",8))}>🌧️<b>Yomg‘ir</b></button><button onClick={()=>mutate(w=>triggerWeather(w,selectedCountryId,"qor",8))}>❄️<b>Qor</b></button><button onClick={()=>mutate(w=>triggerWeather(w,selectedCountryId,"issiq",10))}>♨️<b>Jazirama</b></button><button onClick={()=>mutate(w=>triggerWeather(w,selectedCountryId,"boron",6))}>⚡<b>Bo‘ron</b></button><button onClick={()=>mutate(w=>triggerWeather(w,selectedCountryId,"toshqin",8))}>🌊<b>Toshqin</b></button><button onClick={()=>mutate(w=>triggerWeather(w,selectedCountryId,"yongin",5))}>🔥<b>Yong‘in</b></button></div><h3>Iqtisod</h3><div className="godGrid two"><button onClick={()=>mutate(w=>triggerEconomy(w,selectedCountryId,true))}>📈<b>Iqtisodiy o‘sish</b></button><button onClick={()=>mutate(w=>triggerEconomy(w,selectedCountryId,false))}>📉<b>Inqiroz</b></button></div><h3>AI miya</h3><button className={`wideAction ${world.aiBrain?"on":""}`} onClick={()=>mutate(w=>{w.aiBrain=!w.aiBrain})}>{world.aiBrain?"✓ Gemini qarorlari yoqilgan":"Gemini qarorlarini yoqish"}</button><button className="wideAction" onClick={()=>void aiPulse()}>🧠 Hozir AI qarori yaratish</button><h3>Dunyo fayli</h3><button className="wideAction" onClick={exportWorld}>↓ Dunyoni JSON saqlash</button><button className="wideAction danger" onClick={reset}>⟳ Dunyoni boshidan yaratish</button><button className="wideAction" onClick={async()=>{await fetch('/api/logout',{method:'POST'});location.href='/login';}}>↪ Chiqish</button></>}
      </div>
    </aside>}
  </main>;
}
