"use client";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import WorldCanvas, { CanvasApi } from "./WorldCanvas";
import { createWorld } from "@/lib/seed";
import { sendAgentToType, tickWorld, triggerEconomy, triggerWeather } from "@/lib/engine";
import type { AiAction, Agent, BuildingType, CountryId, WeatherKind, WorldState } from "@/lib/types";

const STORAGE="ai-earth-ultra-v2";
const buildingTypes:BuildingType[]=["home","office","shop","cafe","hospital","school","government","media","market","park","factory"];
function timeLabel(w:WorldState){const h=Math.floor(w.minute/60)%24,m=Math.floor(w.minute%60);return `DAY ${w.day} · ${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}`;}
function relTime(at:number,w:WorldState){const now=w.day*1440+w.minute,d=Math.max(0,now-at);return d<60?`${Math.floor(d)}m`:`${Math.floor(d/60)}h`;}
function deepClone<T>(v:T):T{return JSON.parse(JSON.stringify(v)) as T;}
function load():WorldState|undefined{try{const raw=localStorage.getItem(STORAGE);if(!raw)return;const p=JSON.parse(raw) as WorldState;return p.version===2?p:undefined;}catch{return;}}

export default function WorldApp(){
  const [world,setWorld]=useState<WorldState>(()=>createWorld());const worldRef=useRef(world);const canvasApi=useRef<CanvasApi|null>(null);const [selectedId,setSelectedId]=useState<string>();const [tab,setTab]=useState<"world"|"agents"|"insta"|"aiogram"|"news"|"god">("world");const [aiStatus,setAiStatus]=useState("AI brain ready");const [search,setSearch]=useState("");const [detailOpen,setDetailOpen]=useState(true);const lastFrame=useRef(performance.now());const pulseBusy=useRef(false);
  useEffect(()=>{const saved=load();if(saved){worldRef.current=saved;setWorld(deepClone(saved));}},[]);
  useEffect(()=>{worldRef.current=world;},[world]);
  useEffect(()=>{let raf=0;const run=(now:number)=>{const dt=Math.min(.12,(now-lastFrame.current)/1000);lastFrame.current=now;const w=worldRef.current;if(w.speed>0){tickWorld(w,dt);if(Math.floor(now/250)%4===0)setWorld(deepClone(w));}raf=requestAnimationFrame(run);};raf=requestAnimationFrame(run);return()=>cancelAnimationFrame(raf);},[]);
  useEffect(()=>{const t=setInterval(()=>{try{localStorage.setItem(STORAGE,JSON.stringify(worldRef.current));}catch{}},4000);return()=>clearInterval(t);},[]);
  useEffect(()=>{const t=setInterval(()=>{const w=worldRef.current;if(!w.aiBrain||pulseBusy.current||w.speed===0)return;const absolute=w.day*1440+w.minute;if(absolute-w.aiLastPulse<150)return;void aiPulse();},12000);return()=>clearInterval(t);},[]);
  const selected=useMemo(()=>world.agents.find(a=>a.id===selectedId),[world.agents,selectedId]);
  const setSpeed=(speed:0|1|5|20)=>{worldRef.current.speed=speed;setWorld(deepClone(worldRef.current));};
  const mutate=(fn:(w:WorldState)=>void)=>{fn(worldRef.current);setWorld(deepClone(worldRef.current));};
  const select=useCallback((id?:string)=>{setSelectedId(id);if(id){setDetailOpen(true);canvasApi.current?.focusAgent(id);}},[]);
  async function aiPulse(){pulseBusy.current=true;setAiStatus("Gemini is thinking…");const w=worldRef.current;const candidates=[...w.agents].sort((a,b)=>a.aiCooldownUntil-b.aiCooldownUntil).filter(a=>a.aiCooldownUntil<=w.day*1440+w.minute).slice(0,4);if(!candidates.length){pulseBusy.current=false;return;}
    const payload={agents:candidates.map(a=>{const c=w.countries.find(x=>x.id===a.countryId)!;return{id:a.id,name:a.name,job:a.job,personality:a.personality,goal:a.goal,mood:a.mood,activity:a.activity,money:Math.round(a.money),hunger:Math.round(a.hunger),energy:Math.round(a.energy),friends:a.friends.slice(0,4).map(id=>{const p=w.agents.find(x=>x.id===id);return{id,name:p?.name||id};}),memories:a.memories.slice(0,4).map(m=>m.text),country:c.name,weather:c.weather,recentPosts:w.posts.slice(0,5).map(p=>`${p.authorName}: ${p.text}`)}})};
    try{const r=await fetch("/api/think",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await r.json() as {actions?:AiAction[];source?:string;warning?:string};applyAi(data.actions||[]);w.aiLastPulse=w.day*1440+w.minute;setAiStatus(data.source==="gemini"?"Gemini brain active":"Local brain fallback");if(data.warning)setAiStatus(`Fallback · ${data.warning.slice(0,55)}`);}catch{setAiStatus("Local brain fallback");}finally{pulseBusy.current=false;setWorld(deepClone(w));}}
  function applyAi(actions:AiAction[]){const w=worldRef.current;for(const action of actions){const a=w.agents.find(x=>x.id===action.agentId);if(!a)continue;a.aiCooldownUntil=w.day*1440+w.minute+180;a.thought=action.text;a.memories.unshift({id:`ai-${Date.now()}-${a.id}`,at:w.day*1440+w.minute,text:action.text,importance:4});a.memories=a.memories.slice(0,12);if(action.action==="post"){w.posts.unshift({id:`ai-post-${Date.now()}-${a.id}`,network:"insta",authorId:a.id,authorName:a.name,at:w.day*1440+w.minute,text:action.text,likes:0,comments:[]});}else if(action.action==="dm"&&action.targetAgentId){const b=w.agents.find(x=>x.id===action.targetAgentId);if(b)w.messages.unshift({id:`ai-dm-${Date.now()}-${a.id}`,fromId:a.id,toId:b.id,fromName:a.name,toName:b.name,at:w.day*1440+w.minute,text:action.text});}else if(action.action==="comment"){const post=w.posts.find(p=>p.authorId!==a.id);if(post)post.comments.push({id:`c-${Date.now()}-${a.id}`,authorId:a.id,authorName:a.name,text:action.text});}else if(action.action==="go"&&action.destinationType){sendAgentToType(w,a.id,action.destinationType);}}
    w.posts=w.posts.slice(0,160);w.messages=w.messages.slice(0,160);
  }
  const filtered=world.agents.filter(a=>`${a.name} ${a.job} ${a.countryId}`.toLowerCase().includes(search.toLowerCase()));
  return <main className="app-shell">
    <header className="topbar"><div className="brand"><div className="brand-mark">◎</div><div><b>AI EARTH</b><span>ULTRA · PRIVATE WORLD</span></div></div><div className="clock"><b>{timeLabel(world)}</b><span>{world.agents.filter(a=>a.path.length>0).length} walking · {world.agents.filter(a=>a.activity==="work").length} working</span></div><div className="top-actions"><button className={world.aiBrain?"ai-live":""} onClick={()=>mutate(w=>w.aiBrain=!w.aiBrain)}>{world.aiBrain?"● AI BRAIN ON":"AI BRAIN OFF"}</button><button onClick={()=>void aiPulse()}>Brain pulse</button><button onClick={async()=>{await fetch("/api/logout",{method:"POST"});location.href="/login";}}>Lock</button></div></header>
    <nav className="sidebar">{([['world','◫','World'],['agents','◉','Agents'],['insta','♡','InstaAIgram'],['aiogram','✦','AIogram'],['news','▤','AI News'],['god','⚡','God Mode']] as const).map(([id,icon,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}><span>{icon}</span><small>{label}</small></button>)}</nav>
    <section className="stage"><WorldCanvas worldRef={worldRef} selectedId={selectedId} onSelect={select} apiRef={canvasApi}/><div className="stage-tools"><button onClick={()=>canvasApi.current?.reset()}>Planet view</button>{world.countries.map(c=><button key={c.id} onClick={()=>canvasApi.current?.focusCountry(c.id)}>{c.name}</button>)}</div><div className="speed"><span>TIME</span>{([0,1,5,20] as const).map(s=><button key={s} className={world.speed===s?"active":""} onClick={()=>setSpeed(s)}>{s===0?"Ⅱ":`${s}×`}</button>)}</div><div className="ai-status">{aiStatus}</div></section>
    {tab!=="world"&&<aside className="panel left-panel"><button className="close" onClick={()=>setTab("world")}>×</button>{tab==="agents"&&<AgentsPanel agents={filtered} search={search} setSearch={setSearch} select={select}/>} {tab==="insta"&&<PostsPanel title="InstaAIgram" posts={world.posts.filter(p=>p.network==="insta")} w={world}/>} {tab==="aiogram"&&<MessagesPanel w={world}/>} {tab==="news"&&<NewsPanel w={world}/>} {tab==="god"&&<GodPanel w={world} mutate={mutate} reset={()=>{const n=createWorld(Date.now()%1000000);worldRef.current=n;setWorld(deepClone(n));setSelectedId(undefined);localStorage.removeItem(STORAGE);}}/>}</aside>}
    {selected&&detailOpen&&<AgentDetail a={selected} w={world} close={()=>setDetailOpen(false)} follow={()=>canvasApi.current?.focusAgent(selected.id)} send={(type)=>mutate(w=>sendAgentToType(w,selected.id,type))}/>} 
  </main>;
}
function AgentsPanel({agents,search,setSearch,select}:{agents:Agent[];search:string;setSearch:(s:string)=>void;select:(id:string)=>void}){return <><div className="panel-head"><span className="eyebrow">POPULATION</span><h2>100 autonomous citizens</h2><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, job, country…"/></div><div className="agent-list">{agents.map(a=><button key={a.id} onClick={()=>select(a.id)}><i className={`mood ${a.mood}`}/><div><b>{a.name}</b><span>{a.job} · {a.countryId}</span></div><em>{a.activity}</em></button>)}</div></>}
function PostsPanel({title,posts,w}:{title:string;posts:WorldState["posts"];w:WorldState}){return <><div className="panel-head"><span className="eyebrow">SOCIAL NETWORK</span><h2>{title}</h2><p>Posts are created by citizens, not by you.</p></div><div className="feed">{posts.length===0&&<div className="empty">The network is quiet. Let time run or press Brain pulse.</div>}{posts.map(p=><article key={p.id}><div className="post-top"><b>{p.authorName}</b><span>{relTime(p.at,w)} ago</span></div><p>{p.text}</p><footer>♡ {p.likes} · ◌ {p.comments.length}</footer>{p.comments.slice(-2).map(c=><small key={c.id}><b>{c.authorName}</b> {c.text}</small>)}</article>)}</div></>}
function MessagesPanel({w}:{w:WorldState}){return <><div className="panel-head"><span className="eyebrow">PRIVATE CHATTER</span><h2>AIogram</h2><p>Citizens meet and message each other autonomously.</p></div><div className="feed">{w.messages.length===0&&<div className="empty">No conversations yet.</div>}{w.messages.map(m=><article key={m.id} className="message"><div className="post-top"><b>{m.fromName} → {m.toName}</b><span>{relTime(m.at,w)} ago</span></div><p>{m.text}</p></article>)}</div></>}
function NewsPanel({w}:{w:WorldState}){return <><div className="panel-head"><span className="eyebrow">WORLD HISTORY</span><h2>AI News</h2></div><div className="feed">{w.events.map(e=><article key={e.id}><div className="post-top"><b>{e.type.toUpperCase()}</b><span>{e.countryId||"world"}</span></div><p>{e.text}</p></article>)}</div></>}
function GodPanel({w,mutate,reset}:{w:WorldState;mutate:(fn:(w:WorldState)=>void)=>void;reset:()=>void}){const [country,setCountry]=useState<CountryId>("astra");return <><div className="panel-head"><span className="eyebrow danger">GOD MODE</span><h2>Change their world</h2><p>Citizens do not know you exist. Events change their decisions.</p><select value={country} onChange={e=>setCountry(e.target.value as CountryId)}>{w.countries.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="god-grid">{([['clear','☀','Clear'],['rain','☂','Rain'],['heat','♨','Heat'],['storm','ϟ','Storm'],['flood','≈','Flood'],['fire','▲','Fire']] as Array<[WeatherKind,string,string]>).map(([kind,icon,label])=><button key={kind} onClick={()=>mutate(w=>triggerWeather(w,country,kind,kind==="clear"?1:6))}><b>{icon}</b><span>{label}</span></button>)}<button onClick={()=>mutate(w=>triggerEconomy(w,country,true))}><b>↗</b><span>Boom</span></button><button onClick={()=>mutate(w=>triggerEconomy(w,country,false))}><b>↘</b><span>Crisis</span></button></div><div className="country-stats">{w.countries.map(c=><div key={c.id}><b>{c.name}</b><span>Weather {c.weather}</span><span>Happiness {Math.round(c.happiness)}%</span><span>Treasury {Math.round(c.treasury).toLocaleString()}</span></div>)}</div><button className="reset-world" onClick={()=>{if(confirm("Reset the whole world and create a new timeline?"))reset();}}>Reset entire timeline</button></>}
function AgentDetail({a,w,close,follow,send}:{a:Agent;w:WorldState;close:()=>void;follow:()=>void;send:(t:BuildingType)=>void}){const c=w.countries.find(x=>x.id===a.countryId)!;return <aside className="agent-detail"><button className="close" onClick={close}>×</button><div className="avatar"><span>{a.name.split(" ").map(x=>x[0]).join("")}</span></div><span className="eyebrow">CITIZEN · {c.name.toUpperCase()}</span><h2>{a.name}</h2><p className="thought">“{a.thought}”</p><div className="chips"><span>{a.job}</span><span>{a.age} y/o</span><span>{a.mood}</span><span>{a.activity}</span></div><div className="meters"><Meter label="Energy" v={a.energy}/><Meter label="Hunger" v={100-a.hunger}/><Meter label="Social" v={a.social}/></div><div className="facts"><div><span>Money</span><b>${a.money.toFixed(0)}</b></div><div><span>Friends</span><b>{a.friends.length}</b></div><div><span>Goal</span><b>{a.goal}</b></div><div><span>Personality</span><b>{a.personality}</b></div></div><button className="follow" onClick={follow}>◎ Follow citizen</button><div className="send-row"><span>Send manually</span><select onChange={e=>{if(e.target.value)send(e.target.value as BuildingType);e.target.value="";}} defaultValue=""><option value="" disabled>Choose place…</option>{buildingTypes.map(t=><option key={t}>{t}</option>)}</select></div><div className="memories"><h3>Memory</h3>{a.memories.length===0?<p>No major memories yet.</p>:a.memories.map(m=><p key={m.id}>{m.text}</p>)}</div></aside>}
function Meter({label,v}:{label:string;v:number}){return <div><span>{label}<b>{Math.round(v)}%</b></span><i><em style={{width:`${Math.max(0,Math.min(100,v))}%`}}/></i></div>}
