"use client";
import { Canvas, useFrame, useThree } from "@react-three/fiber";
import { Html, MapControls, Sky, Stars } from "@react-three/drei";
import * as THREE from "three";
import { useEffect, useMemo, useRef, useState } from "react";
import type { Agent, Building, Country, CountryId, WeatherKind, WorldState } from "@/lib/types";
import { countryAt, terrainHeight, WORLD_D, WORLD_W } from "@/lib/terrain";

type Props={world:WorldState;selectedAgentId:string|null;follow:boolean;onSelectAgent:(id:string)=>void;selectedCountryId:CountryId};
const countryTint:Record<CountryId,THREE.Color>={zarrin:new THREE.Color("#bfa655"),koksaroy:new THREE.Color("#5d99c6"),sahro:new THREE.Color("#bb7854"),navbahor:new THREE.Color("#61a56d"),oqsoy:new THREE.Color("#8f84bd")};
function colorForTerrain(x:number,z:number,h:number){if(h<-.5)return new THREE.Color("#447a8b");if(h<1.6)return new THREE.Color("#c8b982");let base=h>34?new THREE.Color("#e5e7e6"):h>22?new THREE.Color("#8a806e"):h>10?new THREE.Color("#607b52"):new THREE.Color("#527b45");const cid=countryAt(x,z);if(cid)base=base.clone().lerp(countryTint[cid],.12);return base;}
function Terrain(){const geom=useMemo(()=>{const cols=120,rows=84,g=new THREE.PlaneGeometry(WORLD_W,WORLD_D,cols,rows);g.rotateX(-Math.PI/2);const pos=g.attributes.position as THREE.BufferAttribute;const colors:number[]=[];for(let i=0;i<pos.count;i++){const x=pos.getX(i),z=pos.getZ(i),h=terrainHeight(x,z);pos.setY(i,h);const c=colorForTerrain(x,z,h);colors.push(c.r,c.g,c.b);}g.setAttribute("color",new THREE.Float32BufferAttribute(colors,3));g.computeVertexNormals();return g;},[]);return <mesh geometry={geom} receiveShadow><meshStandardMaterial vertexColors roughness={.96} metalness={0}/></mesh>}
function Ocean(){const ref=useRef<THREE.Mesh>(null);useFrame(({clock})=>{if(ref.current){ref.current.position.y=-1.25+Math.sin(clock.elapsedTime*.45)*.12;}});return <mesh ref={ref} rotation={[-Math.PI/2,0,0]} position={[0,-1.35,0]} receiveShadow><planeGeometry args={[900,700,1,1]}/><meshPhysicalMaterial color="#3d7890" roughness={.2} metalness={.16} transparent opacity={.82}/></mesh>}
function CountryBorders({countries}:{countries:Country[]}){return <group>{countries.map(c=>{const pts:THREE.Vector3[]=[];for(let i=0;i<c.polygon.length;i++){const a=c.polygon[i]!,b=c.polygon[(i+1)%c.polygon.length]!;for(let k=0;k<18;k++){const t=k/18,x=a.x+(b.x-a.x)*t,z=a.z+(b.z-a.z)*t;pts.push(new THREE.Vector3(x,terrainHeight(x,z)+.55,z));}}pts.push(pts[0]!.clone());const geometry=new THREE.BufferGeometry().setFromPoints(pts);return <line key={c.id} geometry={geometry}><lineBasicMaterial color="#f5e8bf" transparent opacity={.9}/></line>})}</group>}
function Roads({world}:{world:WorldState}){const roads=useMemo(()=>world.countries.flatMap(c=>{const cx=c.center.x,cz=c.center.z;const segments:THREE.Vector3[][]=[];const sample=(x1:number,z1:number,x2:number,z2:number)=>Array.from({length:20},(_,k)=>{const t=k/19,x=x1+(x2-x1)*t,z=z1+(z2-z1)*t;return new THREE.Vector3(x,terrainHeight(x,z)+.28,z)});for(let i=-3;i<=3;i++){const x=cx+i*25;segments.push(sample(x,cz-80,x,cz+80));const z=cz+i*23;segments.push(sample(cx-85,z,cx+85,z));}return segments;}),[world.countries]);return <group>{roads.map((seg,i)=>{const g=new THREE.BufferGeometry().setFromPoints(seg);return <line key={i} geometry={g}><lineBasicMaterial color="#3c4142" transparent opacity={.82}/></line>})}</group>}
function Tree({x,z,s=1}:{x:number;z:number;s?:number}){const y=terrainHeight(x,z);return <group position={[x,y,z]} scale={s}><mesh castShadow position={[0,1.2,0]}><cylinderGeometry args={[.22,.3,2.4,7]}/><meshStandardMaterial color="#6d4d31" roughness={1}/></mesh><mesh castShadow position={[0,3,0]}><icosahedronGeometry args={[1.35,1]}/><meshStandardMaterial color="#315d3b" roughness={1}/></mesh></group>}
function Nature(){const trees=useMemo(()=>{const arr:Array<{x:number;z:number;s:number}>=[];for(let i=0;i<150;i++){const x=-320+((i*83)%640),z=-205+((i*137)%410);const h=terrainHeight(x,z);if(h>2&&h<18&&Math.abs(x)%25>9&&Math.abs(z)%23>8)arr.push({x,z,s:.65+(i%5)*.08});}return arr.slice(0,100);},[]);return <group>{trees.map((t,i)=><Tree key={i} {...t}/>)}</group>}
function CapitalLabels({countries}:{countries:Country[]}){return <>{countries.map(c=><group key={c.id} position={[c.center.x,terrainHeight(c.center.x,c.center.z)+18,c.center.z]}><Html center distanceFactor={28}><div className="capitalLabel"><b>{c.capital}</b><span>{c.name}</span></div></Html></group>)}</>}
function BuildingModel({b,countryColor,night}:{b:Building;countryColor:string;night:boolean}){const y=terrainHeight(b.x,b.z),height=b.type==="park"?.15:b.floors*3.2+2;const wall=b.type==="shifoxona"?"#e6e8e6":b.type==="hukumat"?"#d8cfb7":b.type==="zavod"?"#8f9698":b.type==="kafe"?"#b87858":countryColor;const baseColor=new THREE.Color(wall).lerp(new THREE.Color("#c7c3b8"),.5).getStyle();if(b.type==="park")return <group position={[b.x,y+.05,b.z]}><mesh receiveShadow><boxGeometry args={[b.w,.12,b.d]}/><meshStandardMaterial color="#44784b" roughness={1}/></mesh>{[-4,0,4].map((dx,i)=><group key={i} position={[dx,0,(i%2)*4-2]}><mesh castShadow position={[0,1,0]}><cylinderGeometry args={[.16,.22,2,7]}/><meshStandardMaterial color="#6d4d31"/></mesh><mesh castShadow position={[0,2.5,0]}><icosahedronGeometry args={[1,1]}/><meshStandardMaterial color="#315d3b" roughness={1}/></mesh></group>)}</group>;
  return <group position={[b.x,y,b.z]}><mesh castShadow receiveShadow position={[0,height/2,0]}><boxGeometry args={[b.w,height,b.d]}/><meshStandardMaterial color={baseColor} roughness={.72}/></mesh><mesh castShadow position={[0,height+.5,0]}><boxGeometry args={[b.w*.92,1,b.d*.92]}/><meshStandardMaterial color="#555b5e" roughness={.8}/></mesh>{Array.from({length:Math.min(5,b.floors)}).map((_,i)=><mesh key={i} position={[0,2.2+i*3.1,b.d/2+.03]}><boxGeometry args={[b.w*.7,1.1,.08]}/><meshStandardMaterial color="#8db2c2" emissive="#23333a" emissiveIntensity={night?1.15:.14} metalness={.15} roughness={.28}/></mesh>)}{b.type==="uy"&&<mesh castShadow position={[0,height+1.45,0]} rotation={[0,Math.PI/4,0]}><coneGeometry args={[b.w*.72,2.7,4]}/><meshStandardMaterial color="#70493c" roughness={.9}/></mesh>}{b.type==="shifoxona"&&<group position={[0,height+1.9,0]}><mesh><boxGeometry args={[.8,3,.6]}/><meshStandardMaterial color="#a22b2b"/></mesh><mesh><boxGeometry args={[3,.8,.6]}/><meshStandardMaterial color="#a22b2b"/></mesh></group>}</group>}
function Buildings({world,night}:{world:WorldState;night:boolean}){return <group>{world.buildings.map(b=><BuildingModel key={b.id} b={b} night={night} countryColor={world.countries.find(c=>c.id===b.countryId)?.color||"#aaa"}/>)}</group>}
function Person({agent,selected,onClick}:{agent:Agent;selected:boolean;onClick:()=>void}){const g=useRef<THREE.Group>(null),left=useRef<THREE.Mesh>(null),right=useRef<THREE.Mesh>(null);const moving=agent.path.length>0;useFrame(({clock})=>{if(g.current){const y=terrainHeight(agent.x,agent.z)+.05;g.current.position.lerp(new THREE.Vector3(agent.x,y,agent.z),.28);g.current.rotation.y=agent.heading;}const swing=moving?Math.sin(clock.elapsedTime*8+parseInt(agent.id.split("-")[1]||"0",36))*.6:0;if(left.current)left.current.rotation.x=swing;if(right.current)right.current.rotation.x=-swing;});const skin="#d7a77e";const shirt=countryTint[agent.countryId].clone().offsetHSL(0,.04,selected ? .2 : 0).getStyle();return <group ref={g} position={[agent.x,terrainHeight(agent.x,agent.z),agent.z]} onClick={e=>{e.stopPropagation();onClick();}}><mesh castShadow position={[0,3.55,0]}><sphereGeometry args={[.58,14,10]}/><meshStandardMaterial color={skin} roughness={.72}/></mesh><mesh castShadow position={[0,2.25,0]}><cylinderGeometry args={[.62,.72,1.9,10]}/><meshStandardMaterial color={shirt} roughness={.78}/></mesh><mesh ref={left} castShadow position={[-.38,.75,0]}><cylinderGeometry args={[.2,.22,1.4,8]}/><meshStandardMaterial color="#2e3741" roughness={.9}/></mesh><mesh ref={right} castShadow position={[.38,.75,0]}><cylinderGeometry args={[.2,.22,1.4,8]}/><meshStandardMaterial color="#2e3741" roughness={.9}/></mesh><mesh castShadow position={[-.82,2.2,0]} rotation={[0,0,.15]}><cylinderGeometry args={[.18,.2,1.5,8]}/><meshStandardMaterial color={skin}/></mesh><mesh castShadow position={[.82,2.2,0]} rotation={[0,0,-.15]}><cylinderGeometry args={[.18,.2,1.5,8]}/><meshStandardMaterial color={skin}/></mesh>{selected&&<><mesh position={[0,.08,0]} rotation={[-Math.PI/2,0,0]}><ringGeometry args={[1.2,1.55,32]}/><meshBasicMaterial color="#ffe899" transparent opacity={.9}/></mesh><pointLight position={[0,5,0]} intensity={.45} distance={8} color="#ffe7a0"/></>}</group>}
function Agents({world,selectedAgentId,onSelectAgent}:{world:WorldState;selectedAgentId:string|null;onSelectAgent:(id:string)=>void}){return <group>{world.agents.map(a=><Person key={a.id} agent={a} selected={a.id===selectedAgentId} onClick={()=>onSelectAgent(a.id)}/>)}</group>}
function WeatherFx({weather,country}:{weather:WeatherKind;country:Country}){const count=weather==="yomgir"||weather==="boron"?150:weather==="qor"?100:0;const refs=useRef<THREE.Group>(null);const drops=useMemo(()=>Array.from({length:count},(_,i)=>({x:country.center.x-90+(i*37)%180,z:country.center.z-75+(i*59)%150,y:10+(i*17)%45})),[count,country.center.x,country.center.z]);useFrame((_,dt)=>{if(!refs.current)return;refs.current.children.forEach((o,i)=>{o.position.y-=dt*(weather==="qor"?4:26);if(o.position.y<terrainHeight(o.position.x,o.position.z)+1)o.position.y=drops[i]!.y;});});if(count===0)return null;return <group ref={refs}>{drops.map((d,i)=><mesh key={i} position={[d.x,d.y,d.z]}><boxGeometry args={weather==="qor"?[.22,.22,.22]:[.06,1.4,.06]}/><meshBasicMaterial color={weather==="qor"?"#f7fbff":"#a9d8ed"} transparent opacity={.72}/></mesh>)}</group>}
function HazardFx({country}:{country:Country}){const y=terrainHeight(country.center.x,country.center.z);if(country.weather==="yongin")return <group position={[country.center.x,y+1,country.center.z]}>{Array.from({length:14},(_,i)=>{const a=i*.9,r=12+(i%5)*7;return <mesh key={i} position={[Math.cos(a)*r,1.5,Math.sin(a)*r]}><coneGeometry args={[1.2,4.5,8]}/><meshStandardMaterial color={i%2?"#ff8b31":"#e44924"} emissive="#ff5a1f" emissiveIntensity={1.7}/></mesh>})}<pointLight position={[0,8,0]} intensity={5} distance={80} color="#ff6a2e"/></group>;if(country.weather==="toshqin")return <mesh rotation={[-Math.PI/2,0,0]} position={[country.center.x,y+1.1,country.center.z]}><circleGeometry args={[82,64]}/><meshPhysicalMaterial color="#5f9eb3" transparent opacity={.38} roughness={.18} metalness={.1}/></mesh>;if(country.weather==="issiq")return <pointLight position={[country.center.x,y+35,country.center.z]} intensity={2.2} distance={150} color="#ff9b52"/>;return null}
function CameraRig({world,selectedAgentId,follow}:{world:WorldState;selectedAgentId:string|null;follow:boolean}){const {camera}=useThree();const controls=useRef<any>(null);const prevSelected=useRef<string|null>(null);useFrame(()=>{const a=selectedAgentId?world.agents.find(x=>x.id===selectedAgentId):undefined;if(!a||!controls.current)return;const y=terrainHeight(a.x,a.z);if(prevSelected.current!==selectedAgentId){camera.position.set(a.x+18,y+18,a.z+24);controls.current.target.set(a.x,y+2,a.z);controls.current.update();prevSelected.current=selectedAgentId;}else if(follow){controls.current.target.lerp(new THREE.Vector3(a.x,y+2,a.z),.12);const desired=new THREE.Vector3(a.x+18,y+18,a.z+24);camera.position.lerp(desired,.08);controls.current.update();}});return <MapControls ref={controls} makeDefault enableDamping dampingFactor={.08} minDistance={8} maxDistance={360} maxPolarAngle={Math.PI*.47} target={[0,0,0]}/>}
function SelectedBubble({world,id}:{world:WorldState;id:string|null}){const a=id?world.agents.find(x=>x.id===id):undefined;if(!a)return null;return <group position={[a.x,terrainHeight(a.x,a.z)+5.2,a.z]}><Html center distanceFactor={18}><div className="worldBubble"><b>{a.name}</b><span>{a.thought}</span></div></Html></group>}
function Scene({world,selectedAgentId,follow,onSelectAgent}:Props){const hour=world.minute/60;const daylight=Math.max(.03,Math.sin(Math.PI*(hour-6)/12));const night=daylight<.16;const sunAngle=(hour-6)/24*Math.PI*2;const sun:[number,number,number]=[Math.cos(sunAngle)*180,Math.sin(sunAngle)*150,-95];const bg=new THREE.Color("#07101b").lerp(new THREE.Color("#8fb7c9"),Math.min(1,daylight*1.2)).getStyle();const fog=new THREE.Color("#101b22").lerp(new THREE.Color("#9eb8bb"),Math.min(1,daylight*1.15)).getStyle();return <><color attach="background" args={[bg]}/><fog attach="fog" args={[fog,180,520]}/>{night?<Stars radius={420} depth={80} count={1800} factor={4} saturation={.2} fade speed={.35}/>:<Sky distance={450000} sunPosition={sun} turbidity={8} rayleigh={1.8}/>}<hemisphereLight intensity={.32+daylight*.95} color={night?"#6880a5":"#e8f1ff"} groundColor="#35463b"/><directionalLight castShadow position={sun} intensity={.18+daylight*2.05} color={night?"#8ca2c8":"#fff2d3"} shadow-mapSize-width={2048} shadow-mapSize-height={2048} shadow-camera-left={-260} shadow-camera-right={260} shadow-camera-top={220} shadow-camera-bottom={-220}/><ambientLight intensity={.1+daylight*.16}/><Ocean/><Terrain/><CountryBorders countries={world.countries}/><Roads world={world}/><Nature/><Buildings world={world} night={night}/><CapitalLabels countries={world.countries}/><Agents world={world} selectedAgentId={selectedAgentId} onSelectAgent={onSelectAgent}/>{world.countries.map(c=><group key={`fx-${c.id}`}><WeatherFx weather={c.weather} country={c}/><HazardFx country={c}/></group>)}<SelectedBubble world={world} id={selectedAgentId}/><CameraRig world={world} selectedAgentId={selectedAgentId} follow={follow}/></>}
export default function WorldScene3D(props:Props){const [dpr,setDpr]=useState<[number,number]>([1,1.5]);useEffect(()=>{if(window.devicePixelRatio<1.5)setDpr([1,1.25]);},[]);return <Canvas shadows dpr={dpr} camera={{position:[0,165,245],fov:48,near:.1,far:1200}} gl={{antialias:true,powerPreference:"high-performance",toneMapping:THREE.ACESFilmicToneMapping}}><Scene {...props}/></Canvas>}
