import type { Agent, AgentActivity, AiAction, Building, BuildingType, Country, CountryId, Mood, Vec2, WeatherKind, WorldEvent, WorldState } from "./types";
import { clamp } from "./random";

const PAY:Record<string,number>={"shifokor":18,"o‘qituvchi":10,"dasturchi":16,"jurnalist":11,"oshpaz":9,"sotuvchi":10,"muhandis":15,"dizayner":12,"haydovchi":8,"hamshira":11,"mexanik":10,"bankir":15,"rassom":8,"politsiyachi":12,"quruvchi":11,"davlat xizmatchisi":9,"dehqon":9,"talaba":2,"tadqiqotchi":14,"menejer":17};
const nowOf=(w:WorldState)=>w.day*1440+w.minute;
const dist=(a:Vec2,b:Vec2)=>Math.hypot(a.x-b.x,a.z-b.z);
const byId=(w:WorldState,id?:string)=>id?w.buildings.find(b=>b.id===id):undefined;
const countryOf=(w:WorldState,a:Agent)=>w.countries.find(c=>c.id===a.countryId)!;
const pool=(w:WorldState,cid:CountryId,type?:BuildingType)=>w.buildings.filter(b=>b.countryId===cid&&(!type||b.type===type));
const stablePick=<T,>(items:T[],n:number)=>items.length?items[Math.abs(Math.floor(n))%items.length]:undefined;
function roadPath(a:Vec2,b:Vec2,salt:number):Vec2[]{const mid=salt%2===0?{x:b.x,z:a.z}:{x:a.x,z:b.z};return [mid,b].filter((p,i,arr)=>i===0||dist(p,arr[i-1]!)>1.5);}
function setDestination(w:WorldState,a:Agent,b:Building|undefined,activity:AgentActivity){if(!b)return;const to=b.entrance;a.destinationBuildingId=b.id;a.target=to;a.path=roadPath({x:a.x,z:a.z},to,parseInt(a.id.split("-")[1]||"0",36));a.activity=activity;}
const goHome=(w:WorldState,a:Agent,act:AgentActivity="uyda")=>setDestination(w,a,byId(w,a.homeId),act);
const goWork=(w:WorldState,a:Agent)=>setDestination(w,a,byId(w,a.workId),"yolda");
function goType(w:WorldState,a:Agent,type:BuildingType,act:AgentActivity){setDestination(w,a,stablePick(pool(w,a.countryId,type),w.minute+parseInt(a.id.split("-")[1]||"0",36)),act);}
function mood(a:Agent,c:Country):Mood{if(["boron","toshqin","yongin"].includes(c.weather))return"xavotirli";if(a.energy<25)return"charchagan";if(a.hunger>82)return"jahldor";if(a.money>700&&a.social>70)return"xursand";if(a.activity==="ish")return"diqqatli";return"xotirjam";}
function decide(w:WorldState,a:Agent){const h=(w.minute/60)%24,c=countryOf(w,a);a.lastDecisionAt=nowOf(w);
  if(["boron","toshqin","yongin"].includes(c.weather)){a.thought=`${WEATHER_NAME[c.weather]} xavfli. Xavfsiz joyga qaytishim kerak.`;goHome(w,a,"panoh");return;}
  if(a.hunger>78){a.thought="Qornim ochdi. Ovqatlanishga boraman.";goType(w,a,"kafe","ovqat");return;}
  if(a.energy<20){a.thought="Juda charchadim. Uyga qaytaman.";goHome(w,a,"uyda");return;}
  if(h>=23||h<6){a.thought="Kech bo‘ldi. Uxlash vaqti.";goHome(w,a,"uxlash");return;}
  if(h>=8&&h<17&&a.activity!=="ish"){a.thought=`${a.job} sifatida ishga borishim kerak.`;goWork(w,a);return;}
  if(h>=17&&h<22){const k=(Math.floor(w.minute)+parseInt(a.id.split("-")[1]||"0",36))%5;if(k===0){a.thought="Odamlar bilan ko‘rishgim keldi.";goType(w,a,"park","suhbat");return;}if(k===1&&a.money>20){a.thought="Bozorga kirib chiqaman.";goType(w,a,"bozor","xarid");return;}if(k===2&&a.money>12){a.thought="Kafega boraman.";goType(w,a,"kafe","ovqat");return;}if(k===3){a.thought="Shahar bo‘ylab sayr qilaman.";setDestination(w,a,stablePick(pool(w,a.countryId),w.minute),"sayr");return;}goHome(w,a);return;}
  if(!a.target)goHome(w,a);
}
function arrive(w:WorldState,a:Agent){const b=byId(w,a.destinationBuildingId);if(!b){a.path=[];a.target=undefined;return;}if(b.id===a.workId)a.activity="ish";else if(b.id===a.homeId&&a.activity==="uxlash")a.activity="uxlash";else if(b.id===a.homeId)a.activity="uyda";a.target=undefined;a.path=[];}
function stepMove(w:WorldState,a:Agent,dtMinutes:number){if(!a.path.length)return;const t=a.path[0]!,dx=t.x-a.x,dz=t.z-a.z,d=Math.hypot(dx,dz);const weather=countryOf(w,a).weather;const factor=weather==="yomgir"?.82:weather==="issiq"?.88:weather==="boron"?.55:1;const max=a.speed*factor*dtMinutes/60;a.heading=Math.atan2(dx,dz);if(d<=Math.max(.25,max)){a.x=t.x;a.z=t.z;a.path.shift();if(!a.path.length)arrive(w,a);}else{a.x+=dx/d*max;a.z+=dz/d*max;}}
function activity(w:WorldState,a:Agent,dt:number){const c=countryOf(w,a);a.hunger=clamp(a.hunger+dt*.018);a.energy=a.activity==="uxlash"?clamp(a.energy+dt*.09):clamp(a.energy-dt*.025);if(a.activity==="ish"){a.money+=((PAY[a.job]??10)/60)*dt;a.social=clamp(a.social-dt*.006);}if(a.activity==="ovqat"){a.hunger=clamp(a.hunger-dt*.22);a.money=Math.max(0,a.money-dt*.04);}if(a.activity==="xarid")a.money=Math.max(0,a.money-dt*.06);if(a.activity==="suhbat")a.social=clamp(a.social+dt*.1);if(a.activity==="uyda")a.energy=clamp(a.energy+dt*.018);if(c.weather==="issiq")a.energy=clamp(a.energy-dt*.014);a.mood=mood(a,c);}
const WEATHER_NAME:Record<WeatherKind,string>={ochiq:"ochiq havo",yomgir:"yomg‘ir",issiq:"jazirama",boron:"bo‘ron",toshqin:"toshqin",yongin:"yong‘in",qor:"qor"};
const PLACE_NAME:Record<BuildingType,string>={uy:"uy",ofis:"ofis",dokon:"do‘kon",kafe:"kafe",shifoxona:"shifoxona",maktab:"maktab",hukumat:"hukumat binosi",media:"media markazi",bozor:"bozor",park:"park",zavod:"zavod"};
const TALK=["Bugun ishlaring qanday ketdi?","Shaharda narxlar o‘zgaribdi, sezdingmi?","Kechqurun parkka chiqishni o‘ylayapman.","Bugungi ob-havo rejalarimni o‘zgartirdi.","Ijtimoiy tarmoqdagi yangi gaplarni ko‘rdingmi?","Men yangi maqsad ustida ishlayapman."];
function nearbySocial(w:WorldState,a:Agent){const n=nowOf(w);if(n-a.lastSocialAt<35||a.path.length>0)return;const b=w.agents.find(o=>o.id!==a.id&&o.countryId===a.countryId&&!o.path.length&&dist({x:a.x,z:a.z},{x:o.x,z:o.z})<9&&n-o.lastSocialAt>30);if(!b)return;a.lastSocialAt=n;b.lastSocialAt=n;a.social=clamp(a.social+7);b.social=clamp(b.social+7);if(!a.friends.includes(b.id)&&((parseInt(a.id.split("-")[1]||"0",36)+w.day)%3===0))a.friends.push(b.id);const text=TALK[(Math.floor(w.minute)+parseInt(a.id.split("-")[1]||"0",36))%TALK.length]!;w.messages.unshift({id:`dm-${w.day}-${Math.floor(w.minute)}-${a.id}`,fromId:a.id,toId:b.id,fromName:a.name,toName:b.name,at:n,text});w.messages=w.messages.slice(0,300);}
function passiveSocial(w:WorldState){if(Math.floor(w.minute)%70>1)return;const i=(w.day*17+Math.floor(w.minute/70)*13)%w.agents.length,a=w.agents[i]!,n=nowOf(w);if(n-a.lastSocialAt<30)return;const c=countryOf(w,a);const lines=[`${c.capital} bugun juda jonli. ${a.job} hayoti tinch qo‘ymayapti.`,`Hozir kayfiyatim ${a.mood}. Maqsadim: ${a.goal}.`,c.weather==="ochiq"?"Bugun havo juda yaxshi. Sayr qilishga arziydi.":`${WEATHER_NAME[c.weather]} sabab shaharning ritmi o‘zgardi.`,`Hozirgina ${a.activity} bilan band edim. Shahar haqiqatan ham yashayapti.`];w.posts.unshift({id:`p-${w.day}-${Math.floor(w.minute)}-${a.id}`,network:"insta",authorId:a.id,authorName:a.name,at:n,text:lines[(i+Math.floor(w.minute))%lines.length]!,likes:(i*7)%21,comments:[]});w.posts=w.posts.slice(0,240);a.lastSocialAt=n;}
export function tickWorld(w:WorldState,realSeconds:number){if(w.speed===0)return w;const dt=Math.min(4,realSeconds*w.speed*2.4);w.minute+=dt;while(w.minute>=1440){w.minute-=1440;w.day++;w.events.unshift({id:`kun-${w.day}`,at:nowOf(w),type:"kun",text:`${w.day}-kun boshlandi.`});}
  for(const c of w.countries)if(c.weather!=="ochiq"&&nowOf(w)>=c.weatherUntil){c.weather="ochiq";w.events.unshift({id:`havo-${c.id}-${w.day}-${Math.floor(w.minute)}`,at:nowOf(w),countryId:c.id,type:"havo",text:`${c.name}da ob-havo yana me’yorga qaytdi.`});}
  for(const a of w.agents){stepMove(w,a,dt*60);activity(w,a,dt);const n=nowOf(w);if(!a.path.length&&n-a.lastDecisionAt>18+(parseInt(a.id.split("-")[1]||"0",36)%14))decide(w,a);nearbySocial(w,a);}passiveSocial(w);return w;
}
export function triggerWeather(w:WorldState,cid:CountryId,kind:WeatherKind,durationHours=6){const c=w.countries.find(x=>x.id===cid);if(!c)return;c.weather=kind;c.weatherUntil=nowOf(w)+durationHours*60;if(kind==="toshqin"){c.food=Math.max(0,c.food-12);c.happiness=Math.max(0,c.happiness-7);}if(kind==="yongin"){c.energy=Math.max(0,c.energy-10);c.happiness=Math.max(0,c.happiness-9);}if(kind==="boron")c.energy=Math.max(0,c.energy-7);const text=`${c.name} hududida ${WEATHER_NAME[kind]} boshlandi. Fuqarolar mustaqil reaksiya qilmoqda.`;const e:WorldEvent={id:`e-${Date.now()}`,at:nowOf(w),countryId:cid,type:kind,text};w.events.unshift(e);for(const a of w.agents.filter(x=>x.countryId===cid)){a.lastDecisionAt=-999;a.memories.unshift({id:e.id+"-"+a.id,at:e.at,text,importance:kind==="yomgir"?3:8});a.memories=a.memories.slice(0,16);}}
export function triggerEconomy(w:WorldState,cid:CountryId,boom:boolean){const c=w.countries.find(x=>x.id===cid);if(!c)return;c.treasury+=boom?25000:-18000;c.happiness=clamp(c.happiness+(boom?6:-7));for(const a of w.agents.filter(x=>x.countryId===cid))a.money=Math.max(0,a.money*(boom?1.08:.92));w.events.unshift({id:`eco-${Date.now()}`,at:nowOf(w),countryId:cid,type:"iqtisod",text:`${c.name}da iqtisodiy ${boom?"o‘sish":"inqiroz"} boshlandi.`});}
export function sendAgentToType(w:WorldState,agentId:string,type:BuildingType){const a=w.agents.find(x=>x.id===agentId);if(!a)return;goType(w,a,type,"sayr");a.thought=`O‘zim ${PLACE_NAME[type]} tomon borishga qaror qildim.`;}
export function applyAiActions(w:WorldState,actions:AiAction[]){const n=nowOf(w);for(const act of actions){const a=w.agents.find(x=>x.id===act.agentId);if(!a)continue;if(act.action==="thought"){a.thought=act.text;a.memories.unshift({id:`m-${Date.now()}-${a.id}`,at:n,text:act.text,importance:4});}else if(act.action==="post"){w.posts.unshift({id:`ai-p-${Date.now()}-${a.id}`,network:"insta",authorId:a.id,authorName:a.name,at:n,text:act.text,likes:0,comments:[]});}else if(act.action==="dm"&&act.targetAgentId){const b=w.agents.find(x=>x.id===act.targetAgentId);if(b)w.messages.unshift({id:`ai-dm-${Date.now()}-${a.id}`,fromId:a.id,toId:b.id,fromName:a.name,toName:b.name,at:n,text:act.text});}else if(act.action==="comment"){const p=w.posts.find(p=>p.authorId!==a.id);if(p)p.comments.unshift({id:`c-${Date.now()}-${a.id}`,authorId:a.id,authorName:a.name,text:act.text,at:n});}else if(act.action==="go"&&act.destinationType)sendAgentToType(w,a.id,act.destinationType);a.aiCooldownUntil=n+120;}w.posts=w.posts.slice(0,240);w.messages=w.messages.slice(0,300);}
